# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 11:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_clone_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='micropost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 19, 11, 30, 50, 345591, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='micropost',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 19, 11, 31, 1, 974307, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
